<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SRHPasswordManager_tests.TestNotebook-20240123153713" tests="4" file="SRHPasswordManager_tests.py" time="0.241" timestamp="2024-01-23T15:37:13" failures="0" errors="1" skipped="0">
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_add_entry" time="0.152" timestamp="2024-01-23T15:37:13"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_existing" time="0.002" timestamp="2024-01-23T15:37:13"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_not_existing" time="0.002" timestamp="2024-01-23T15:37:13"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_load_and_decrypt" time="0.085" timestamp="2024-01-23T15:37:13">
		<error type="NameError" message="name 'mock_open' is not defined"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\unittest\python\SRHPasswordManager_tests.py", line 31, in test_load_and_decrypt
    with patch('builtins.open', mock_open(read_data='encrypted_data')) as m:
    ^^^^^^^^^^^^^^^^^
NameError: name 'mock_open' is not defined
]]></error>
	</testcase>
</testsuite>
