<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SRHPasswordManager_tests.TestNotebook-20240123151554" tests="3" file="SRHPasswordManager_tests.py" time="0.151" timestamp="2024-01-23T15:15:54" failures="0" errors="1" skipped="0">
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_existing" time="0.001" timestamp="2024-01-23T15:15:54"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_not_existing" time="0.001" timestamp="2024-01-23T15:15:54"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_add_entry" time="0.149" timestamp="2024-01-23T15:15:54">
		<error type="AttributeError" message="'dict' object has no attribute 'book'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\unittest\python\SRHPasswordManager_tests.py", line 33, in test_add_entry
    print("Notebook content before add_entry:", self.notebook.book)
    ^^^^^^^^^^^^^^^^^
AttributeError: 'dict' object has no attribute 'book'
]]></error>
	</testcase>
</testsuite>
