<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SRHPasswordManager_tests.TestNotebook-20240123135100" tests="3" file="SRHPasswordManager_tests.py" time="0.011" timestamp="2024-01-23T13:51:00" failures="0" errors="1" skipped="0">
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_existing" time="0.006" timestamp="2024-01-23T13:51:00"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_not_existing" time="0.000" timestamp="2024-01-23T13:51:00"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_add_entry" time="0.005" timestamp="2024-01-23T13:51:00">
		<error type="EOFError" message="EOF when reading a line"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\unittest\python\SRHPasswordManager_tests.py", line 25, in test_add_entry
    self.notebook.add_category()
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\main\python\SRHPasswordManager.py", line 87, in add_category
    category = input('Enter the new category (e.g., Websites, Emails): ')
    ^^^^^^^^^^^^^^^^^
EOFError: EOF when reading a line
]]></error>
	</testcase>
</testsuite>
