<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SRHPasswordManager_tests.TestNotebook-20240123144235" tests="3" file="SRHPasswordManager_tests.py" time="0.114" timestamp="2024-01-23T14:42:35" failures="0" errors="1" skipped="0">
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_existing" time="0.001" timestamp="2024-01-23T14:42:35"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_not_existing" time="0.001" timestamp="2024-01-23T14:42:35"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_add_entry" time="0.112" timestamp="2024-01-23T14:42:35">
		<error type="KeyError" message="'Websites'"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\unittest\python\SRHPasswordManager_tests.py", line 33, in test_add_entry
    self.assertEqual(self.notebook.book['Websites']['amazon.com'], expected_entry)
    ^^^^^^^^^^^^^^^^^
KeyError: 'Websites'
]]></error>
	</testcase>
</testsuite>
