<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="SRHPasswordManager_tests.TestNotebook-20240123144007" tests="3" file="SRHPasswordManager_tests.py" time="0.112" timestamp="2024-01-23T14:40:08" failures="1" errors="0" skipped="0">
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_existing" time="0.001" timestamp="2024-01-23T14:40:08"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_check_for_file_not_existing" time="0.001" timestamp="2024-01-23T14:40:08"/>
	<testcase classname="SRHPasswordManager_tests.TestNotebook" name="test_add_entry" time="0.110" timestamp="2024-01-23T14:40:07">
		<failure type="AssertionError" message="None != {'Username': 'john_doe', 'Password': 'password123'}"><![CDATA[Traceback (most recent call last):
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 57, in testPartExecutor
    yield
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 623, in run
    self._callTestMethod(testMethod)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 579, in _callTestMethod
    if method() is not None:
    ^^^^^^^^^^^^^^^^^
  File "c:\users\acer\documents\github\srhpasswordmanager\src\unittest\python\SRHPasswordManager_tests.py", line 34, in test_add_entry
    self.assertEqual(self.notebook.book.get('Websites', {}).get('amazon.com'), expected_entry)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 873, in assertEqual
    assertion_func(first, second, msg=msg)
    ^^^^^^^^^^^^^^^^^
  File "C:\Users\Acer\anaconda3\Lib\unittest\case.py", line 866, in _baseAssertEqual
    raise self.failureException(msg)
    ^^^^^^^^^^^^^^^^^
AssertionError: None != {'Username': 'john_doe', 'Password': 'password123'}
]]></failure>
	</testcase>
</testsuite>
